---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-source-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/nfs/data/repo-source
    server: 10.241.64.4
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-source-pvc  
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: repo-source-pv
...
